#############################################################################
# Makefile for building: TotalReqall.app/Contents/MacOS/TotalReqall
# Generated by qmake (3.1) (Qt 5.15.1)
# Project:  ../TotalReqall.pro
# Template: app
# Command: /usr/local/opt/qt/bin/qmake -o Makefile ../TotalReqall.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I../../TotalReqall -I. -I/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.15.1/lib
QMAKE         = /usr/local/opt/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/opt/qt/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/opt/qt/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = TotalReqall1.0.0
DISTDIR = /Users/travis/build/LorenDB/TotalReqall/build/.tmp/TotalReqall1.0.0
LINK          = /Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/5.15.1/lib -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../Bible.cpp \
		../ChooseReferenceWidget.cpp \
		../MainWindow.cpp \
		../MemorizeEdit.cpp \
		../MemorizeWidget.cpp \
		../main.cpp qrc_bible.cpp \
		moc_Bible.cpp \
		moc_ChooseReferenceWidget.cpp \
		moc_MainWindow.cpp \
		moc_MemorizeEdit.cpp \
		moc_MemorizeWidget.cpp
OBJECTS       = Bible.o \
		ChooseReferenceWidget.o \
		MainWindow.o \
		MemorizeEdit.o \
		MemorizeWidget.o \
		main.o \
		qrc_bible.o \
		moc_Bible.o \
		moc_ChooseReferenceWidget.o \
		moc_MainWindow.o \
		moc_MemorizeEdit.o \
		moc_MemorizeWidget.o
DIST          = /usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_post.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/resources_functions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/lex.prf \
		../../TotalReqall.pro ../AppInfo.h \
		../Bible.h \
		../ChooseReferenceWidget.h \
		../MainWindow.h \
		../MemorizeEdit.h \
		../MemorizeWidget.h ../Bible.cpp \
		../ChooseReferenceWidget.cpp \
		../MainWindow.cpp \
		../MemorizeEdit.cpp \
		../MemorizeWidget.cpp \
		../main.cpp
QMAKE_TARGET  = TotalReqall
DESTDIR       = 
TARGET        = TotalReqall.app/Contents/MacOS/TotalReqall

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15.6
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode-12.1.GM.seed.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/travis/build/LorenDB/TotalReqall/TotalReqall.pro


include /usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

TotalReqall.app/Contents/MacOS/TotalReqall:  $(OBJECTS)  
	@test -d TotalReqall.app/Contents/MacOS/ || mkdir -p TotalReqall.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../TotalReqall.pro /usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_post.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/resources_functions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.15.1/mkspecs/features/lex.prf \
		../TotalReqall.pro \
		../bible.qrc \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Resources/QtGui.prl \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile ../TotalReqall.pro
/usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/qdevice.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3drender_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/spec_post.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/resources_functions.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/5.15.1/mkspecs/features/lex.prf:
../TotalReqall.pro:
../bible.qrc:
/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Resources/QtGui.prl:
/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../TotalReqall.pro

qmake_all: FORCE

TotalReqall.app/Contents/PkgInfo: 
	@test -d TotalReqall.app/Contents || mkdir -p TotalReqall.app/Contents
	@$(DEL_FILE) TotalReqall.app/Contents/PkgInfo
	@echo "APPL????" > TotalReqall.app/Contents/PkgInfo
TotalReqall.app/Contents/Resources/empty.lproj: 
	@test -d TotalReqall.app/Contents/Resources || mkdir -p TotalReqall.app/Contents/Resources
	@touch TotalReqall.app/Contents/Resources/empty.lproj
	
TotalReqall.app/Contents/Info.plist: 
	@test -d TotalReqall.app/Contents || mkdir -p TotalReqall.app/Contents
	@$(DEL_FILE) TotalReqall.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.TotalReqall,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.TotalReqall,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,TotalReqall,g" -e "s,@LIBRARY@,TotalReqall,g" -e "s,\$${EXECUTABLE_NAME},TotalReqall,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang/Info.plist.app >TotalReqall.app/Contents/Info.plist

all: Makefile \
		TotalReqall.app/Contents/PkgInfo \
		TotalReqall.app/Contents/Resources/empty.lproj \
		TotalReqall.app/Contents/Info.plist TotalReqall.app/Contents/MacOS/TotalReqall

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../bible.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Cellar/qt/5.15.1/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../AppInfo.h ../Bible.h ../ChooseReferenceWidget.h ../MainWindow.h ../MemorizeEdit.h ../MemorizeWidget.h $(DISTDIR)/
	$(COPY_FILE) --parents ../Bible.cpp ../ChooseReferenceWidget.cpp ../MainWindow.cpp ../MemorizeEdit.cpp ../MemorizeWidget.cpp ../main.cpp $(DISTDIR)/
	$(COPY_FILE) --parents TotalReqall_en_US.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r TotalReqall.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_bible.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_bible.cpp
qrc_bible.cpp: ../bible.qrc \
		/usr/local/Cellar/qt/5.15.1/bin/rcc \
		../resources/bible.txt
	/usr/local/Cellar/qt/5.15.1/bin/rcc -name bible ../bible.qrc -o qrc_bible.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Cellar/qt/5.15.1/mkspecs/features/data/dummy.cpp
	/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h /usr/local/Cellar/qt/5.15.1/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_Bible.cpp moc_ChooseReferenceWidget.cpp moc_MainWindow.cpp moc_MemorizeEdit.cpp moc_MemorizeWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Bible.cpp moc_ChooseReferenceWidget.cpp moc_MainWindow.cpp moc_MemorizeEdit.cpp moc_MemorizeWidget.cpp
moc_Bible.cpp: ../Bible.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QStringList \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qstringlist.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qtimer.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.15.1/bin/moc
	/usr/local/Cellar/qt/5.15.1/bin/moc $(DEFINES) --include /Users/travis/build/LorenDB/TotalReqall/build/moc_predefs.h -I/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang -I/Users/travis/build/LorenDB/TotalReqall -I/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Cellar/qt/5.15.1/lib ../Bible.h -o moc_Bible.cpp

moc_ChooseReferenceWidget.cpp: ../ChooseReferenceWidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QStringList \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qstringlist.h \
		../Bible.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qtimer.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.15.1/bin/moc
	/usr/local/Cellar/qt/5.15.1/bin/moc $(DEFINES) --include /Users/travis/build/LorenDB/TotalReqall/build/moc_predefs.h -I/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang -I/Users/travis/build/LorenDB/TotalReqall -I/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Cellar/qt/5.15.1/lib ../ChooseReferenceWidget.h -o moc_ChooseReferenceWidget.cpp

moc_MainWindow.cpp: ../MainWindow.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QAction \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qaction.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QMenu \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qmenu.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QStatusBar \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qstatusbar.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../ChooseReferenceWidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QStringList \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qstringlist.h \
		../Bible.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qtimer.h \
		../MemorizeWidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers/QKeyEvent \
		/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers/qevent.h \
		../MemorizeEdit.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qtextedit.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.15.1/bin/moc
	/usr/local/Cellar/qt/5.15.1/bin/moc $(DEFINES) --include /Users/travis/build/LorenDB/TotalReqall/build/moc_predefs.h -I/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang -I/Users/travis/build/LorenDB/TotalReqall -I/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Cellar/qt/5.15.1/lib ../MainWindow.h -o moc_MainWindow.cpp

moc_MemorizeEdit.cpp: ../MemorizeEdit.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers/QKeyEvent \
		/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers/qevent.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.15.1/bin/moc
	/usr/local/Cellar/qt/5.15.1/bin/moc $(DEFINES) --include /Users/travis/build/LorenDB/TotalReqall/build/moc_predefs.h -I/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang -I/Users/travis/build/LorenDB/TotalReqall -I/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Cellar/qt/5.15.1/lib ../MemorizeEdit.h -o moc_MemorizeEdit.cpp

moc_MemorizeWidget.cpp: ../MemorizeWidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers/QKeyEvent \
		/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QStringList \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qstringlist.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../MemorizeEdit.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qtextedit.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.15.1/bin/moc
	/usr/local/Cellar/qt/5.15.1/bin/moc $(DEFINES) --include /Users/travis/build/LorenDB/TotalReqall/build/moc_predefs.h -I/usr/local/Cellar/qt/5.15.1/mkspecs/macx-clang -I/Users/travis/build/LorenDB/TotalReqall -I/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode-12.1.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Cellar/qt/5.15.1/lib ../MemorizeWidget.h -o moc_MemorizeWidget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

Bible.o: ../Bible.cpp ../Bible.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QStringList \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qstringlist.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QTextStream \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qtextstream.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QByteArray \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qbytearray.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bible.o ../Bible.cpp

ChooseReferenceWidget.o: ../ChooseReferenceWidget.cpp ../ChooseReferenceWidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QStringList \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qstringlist.h \
		../Bible.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChooseReferenceWidget.o ../ChooseReferenceWidget.cpp

MainWindow.o: ../MainWindow.cpp ../MainWindow.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QAction \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qaction.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QMenu \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qmenu.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QStatusBar \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qstatusbar.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../ChooseReferenceWidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QStringList \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qstringlist.h \
		../Bible.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qtimer.h \
		../MemorizeWidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers/QKeyEvent \
		/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers/qevent.h \
		../MemorizeEdit.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qtextedit.h \
		../AppInfo.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o ../MainWindow.cpp

MemorizeEdit.o: ../MemorizeEdit.cpp ../MemorizeEdit.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers/QKeyEvent \
		/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MemorizeEdit.o ../MemorizeEdit.cpp

MemorizeWidget.o: ../MemorizeWidget.cpp ../MemorizeWidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers/QKeyEvent \
		/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QStringList \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qstringlist.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../MemorizeEdit.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MemorizeWidget.o ../MemorizeWidget.cpp

main.o: ../main.cpp /usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../MainWindow.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QAction \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qaction.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QMenu \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qmenu.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QStatusBar \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qstatusbar.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QWidget \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qwidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qgridlayout.h \
		../ChooseReferenceWidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QStringList \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qstringlist.h \
		../Bible.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QFile \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qtimer.h \
		../MemorizeWidget.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.15.1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers/QKeyEvent \
		/usr/local/Cellar/qt/5.15.1/lib/QtGui.framework/Headers/qevent.h \
		../MemorizeEdit.h \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.15.1/lib/QtWidgets.framework/Headers/qtextedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../main.cpp

qrc_bible.o: qrc_bible.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_bible.o qrc_bible.cpp

moc_Bible.o: moc_Bible.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Bible.o moc_Bible.cpp

moc_ChooseReferenceWidget.o: moc_ChooseReferenceWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ChooseReferenceWidget.o moc_ChooseReferenceWidget.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_MemorizeEdit.o: moc_MemorizeEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MemorizeEdit.o moc_MemorizeEdit.cpp

moc_MemorizeWidget.o: moc_MemorizeWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MemorizeWidget.o moc_MemorizeWidget.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/TotalReqall/bin || mkdir -p $(INSTALL_ROOT)/opt/TotalReqall/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/TotalReqall/bin/TotalReqall.app
	
	$(QINSTALL) TotalReqall.app $(INSTALL_ROOT)/opt/TotalReqall/bin/TotalReqall.app
	-$(STRIP) $(INSTALL_ROOT)/opt/TotalReqall/bin/TotalReqall.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/TotalReqall/bin/TotalReqall.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/TotalReqall/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

